trigger:
  branches:
    include:
      - master
      - dev

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "windows-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8.5"
    displayName: "Use Python $(python.version)"

  - task: PythonScript@0
    inputs:
      scriptSource: "filePath"
      scriptPath: "test.py"
      workingDirectory: "dev/build"
      displayName: "Running test.py"
