trigger:
- master
- dev

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: windows-2019

steps:

- task: DocFxTask@0
  inputs:
    solution: 'dev/docfx.json'

- task: DocFxTask@0
  inputs:
    solution: 'support/docfx.json'