trigger:
  branches:
    include:
      - withapi

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "windows-latest"

steps:
  - task: CmdLine@2
    inputs:
      script: |
        git clone https://github.com/simplic/documentation -b withapi

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8.5"
    displayName: "Use Python $(python.version)"

  - task: PythonScript@0
    inputs:
      scriptSource: "filePath"
      scriptPath: "_test.py"
      workingDirectory: "D:/a/1/s/documentation/dev/build"
      displayName: "Running test.py"
