trigger:
  branches:
    include:
      - withapi

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "windows-latest"

steps:
  - checkout: self
    persistCredentials: true

  - task: CmdLine@2
    inputs:
      script: |
        git clone https://$(git_user):$(git_pass)@github.com/simplic/documentation -b withapi D:/documentation
    displayName: "Cloning documentation repository"

  - task: CmdLine@2
    inputs:
      script: |
        git clone https://$(git_user):$(git_pass)@github.com/simplic/simplic.github.io -b withapi D:/simplic.github.io
    displayName: "Cloning simplic.github.io repository"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8.5"
    displayName: "Use Python $(python.version)"

  - task: CmdLine@2
    inputs:
      script: |
        git config --system core.longpaths true
        cd D:/documentation
        cd dev
        cd build
        pip install -r requirements.txt
        choco install docfx -y
        python build.py --git-user $(git_user) --git-pass $(git_pass) --ftp-user $(ftp_user) --ftp-pass $(ftp_pass)
    displayName: "Generate API Documentation"

  - task: CmdLine@2
    inputs:
      script: |
        cd D:/documentation
        cd dev
        docfx --serve
        cd ../support
        docfx --serve
        cd ../user
        docfx --serve
    displayName: "Compiling html files"

  - task: CmdLine@2
    inputs:
      script: |
        cd D:/documentation/_site
        copy *.* /y D:/simplic.github.io
    displayName: "Copying html files to simplic.github.io (local folder)"

  - task: CmdLine@2
    inputs:
      script: |
        cd D:/simplic.github.io
        dir /s /b /o:gn
        git add .
        git commit -m 'at pipeline: Comitting compiled html files'
        git push
    displayName: "Test if files were copied and push"
