trigger:
- master
- dev

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: windows-2019

steps:

- task: DocFxTask@0
  inputs:
    solution: 'docfx.json'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'angular_doc'
    Contents: '**'
    TargetFolder: '_site/angular_doc'

